version: "3.9"
services:

  loxotron_ingress:
    container_name: loxotron_ingress
    restart: unless-stopped
    image: nginx:1.23.3
    ports:
      - 80:80
    volumes:
      - ./ingress/default.conf:/etc/nginx/conf.d/default.conf

  loxotron_backend:
    container_name: loxotron_api
    restart: unless-stopped
    image: loxotron_api:0.0
    build: ../../backend

  loxotron_backend_db:
    container_name: loxotron_db
    restart: unless-stopped
    image: mongo:4.4.19-rc0-focal
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  loxotron_backend_db_admin:
    container_name: loxotron_db_admin
    restart: unless-stopped
    image: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@loxotron_backend_db:27017/

  loxotron_frontend:
    container_name: loxotron_front
    restart: unless-stopped
    image: loxotron_front:0.0
    build: ../../frontend
